export const MESSAGE_BUS_VERSION = '0.1'
export const BUS_CHANNEL_SETUP_INIT = 'BUS_CHANNEL_SETUP_INIT'
export const BUS_CHANNEL_INIT_ACK = 'BUS_CHANNEL_INIT_ACK'
export const BUS_CHANNEL_RESET = 'BUS_CHANNEL_RESET'
